### PR TITLE
fix: Remove duplicate Molecule test section and fix undefined functions in test.sh

- Removed duplicate Molecule test section (lines 273-309 were exact duplicate of 236-271)
- Fixed undefined function calls (print_test_header, print_test_result, command_exists)
- Replaced undefined functions with existing ones (print_step, print_success, print_error, print_warning)
- Added check for zero roles with molecule scenarios
- Updated summary section to include Molecule tests when --molecule flag is used
- Reduced file from 324 to 293 lines

Closes #54

Co-authored-by: Skogix <Skogix@users.noreply.github.com>

### LINKED ISSUE #54: time to fix the molecule-thingy
@claude

time to fix the molecule-thingy

### PR DESCRIPTION
**Pull request by Skogix**

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -234,78 +234,45 @@ fi
...
 # Test 5: Molecule Tests (optional)
 if [ "$RUN_MOLECULE" = true ]; then
-  print_test_header "Molecule Role Tests"
-  
-  if ! command_exists molecule; then
-    echo -e "${YELLOW}molecule is not installed. Install with: pip install molecule molecule-plugins[docker]${NC}"
-    print_test_result "Molecule Tests" "SKIP"
-  else
-    echo -e "${BLUE}Testing roles with Molecule...${NC}"
-    MOLECULE_FAILED=0
```
Comment (Skogix) [inline test.sh]:
```
````

````
```
